namespace QuanLy_Karaoke
{
    partial class frmTrangChu
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges11 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges12 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges13 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges14 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmTrangChu));
            this.bunifuFormDock1 = new Bunifu.UI.WinForms.BunifuFormDock();
            this.bunifuShadowPanel1 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.btn_size = new Bunifu.UI.WinForms.BunifuImageButton();
            this.btn_Mini = new Bunifu.UI.WinForms.BunifuImageButton();
            this.btn_Thoat = new Bunifu.UI.WinForms.BunifuImageButton();
            this.bunifuShadowPanel2 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.btn_CaiDat = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_ThongKe = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_KhoHang = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_KhachHang = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_ThanhToan = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_PhongHat = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_TongQuan = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.panel1 = new System.Windows.Forms.Panel();
            this.lb_ChucVu = new System.Windows.Forms.Label();
            this.lb_TenNV = new System.Windows.Forms.Label();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.bunifuShadowPanel3 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.pnl_Con = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuImageButton1 = new Bunifu.UI.WinForms.BunifuImageButton();
            this.panel2 = new System.Windows.Forms.Panel();
            this.panel3 = new System.Windows.Forms.Panel();
            this.bunifuShadowPanel1.SuspendLayout();
            this.bunifuShadowPanel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.bunifuShadowPanel3.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuFormDock1
            // 
            this.bunifuFormDock1.AllowFormDragging = true;
            this.bunifuFormDock1.AllowFormDropShadow = true;
            this.bunifuFormDock1.AllowFormResizing = false;
            this.bunifuFormDock1.AllowHidingBottomRegion = true;
            this.bunifuFormDock1.AllowOpacityChangesWhileDragging = false;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.BottomBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.LeftBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.RightBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.TopBorder.ShowBorder = true;
            this.bunifuFormDock1.ContainerControl = this;
            this.bunifuFormDock1.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
            this.bunifuFormDock1.DockingIndicatorsOpacity = 0.5D;
            this.bunifuFormDock1.DockingOptions.DockAll = true;
            this.bunifuFormDock1.DockingOptions.DockBottomLeft = true;
            this.bunifuFormDock1.DockingOptions.DockBottomRight = true;
            this.bunifuFormDock1.DockingOptions.DockFullScreen = true;
            this.bunifuFormDock1.DockingOptions.DockLeft = true;
            this.bunifuFormDock1.DockingOptions.DockRight = true;
            this.bunifuFormDock1.DockingOptions.DockTopLeft = true;
            this.bunifuFormDock1.DockingOptions.DockTopRight = true;
            this.bunifuFormDock1.FormDraggingOpacity = 0.9D;
            this.bunifuFormDock1.ParentForm = this;
            this.bunifuFormDock1.ShowCursorChanges = true;
            this.bunifuFormDock1.ShowDockingIndicators = false;
            this.bunifuFormDock1.TitleBarOptions.AllowFormDragging = true;
            this.bunifuFormDock1.TitleBarOptions.BunifuFormDock = this.bunifuFormDock1;
            this.bunifuFormDock1.TitleBarOptions.DoubleClickToExpandWindow = true;
            this.bunifuFormDock1.TitleBarOptions.TitleBarControl = null;
            this.bunifuFormDock1.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // bunifuShadowPanel1
            // 
            this.bunifuShadowPanel1.BackColor = System.Drawing.Color.Silver;
            this.bunifuShadowPanel1.BorderColor = System.Drawing.Color.DimGray;
            this.bunifuShadowPanel1.BorderRadius = 1;
            this.bunifuShadowPanel1.BorderThickness = 1;
            this.bunifuShadowPanel1.Controls.Add(this.btn_size);
            this.bunifuShadowPanel1.Controls.Add(this.btn_Mini);
            this.bunifuShadowPanel1.Controls.Add(this.btn_Thoat);
            this.bunifuShadowPanel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuShadowPanel1.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.bunifuShadowPanel1.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuShadowPanel1.Name = "bunifuShadowPanel1";
            this.bunifuShadowPanel1.PanelColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel1.PanelColor2 = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel1.ShadowColor = System.Drawing.Color.DarkGray;
            this.bunifuShadowPanel1.ShadowDept = 2;
            this.bunifuShadowPanel1.ShadowDepth = 0;
            this.bunifuShadowPanel1.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel1.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel1.Size = new System.Drawing.Size(800, 23);
            this.bunifuShadowPanel1.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel1.TabIndex = 0;
            // 
            // btn_size
            // 
            this.btn_size.ActiveImage = null;
            this.btn_size.AllowAnimations = true;
            this.btn_size.AllowBuffering = false;
            this.btn_size.AllowToggling = false;
            this.btn_size.AllowZooming = true;
            this.btn_size.AllowZoomingOnFocus = false;
            this.btn_size.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btn_size.BackColor = System.Drawing.Color.WhiteSmoke;
            this.btn_size.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_size.ErrorImage = ((System.Drawing.Image)(resources.GetObject("btn_size.ErrorImage")));
            this.btn_size.FadeWhenInactive = false;
            this.btn_size.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.btn_size.Image = ((System.Drawing.Image)(resources.GetObject("btn_size.Image")));
            this.btn_size.ImageActive = null;
            this.btn_size.ImageLocation = null;
            this.btn_size.ImageMargin = 0;
            this.btn_size.ImageSize = new System.Drawing.Size(19, 16);
            this.btn_size.ImageZoomSize = new System.Drawing.Size(20, 17);
            this.btn_size.InitialImage = ((System.Drawing.Image)(resources.GetObject("btn_size.InitialImage")));
            this.btn_size.Location = new System.Drawing.Point(751, 3);
            this.btn_size.Name = "btn_size";
            this.btn_size.Rotation = 0;
            this.btn_size.ShowActiveImage = true;
            this.btn_size.ShowCursorChanges = true;
            this.btn_size.ShowImageBorders = true;
            this.btn_size.ShowSizeMarkers = false;
            this.btn_size.Size = new System.Drawing.Size(20, 17);
            this.btn_size.TabIndex = 2;
            this.btn_size.ToolTipText = "";
            this.btn_size.WaitOnLoad = false;
            this.btn_size.Zoom = 0;
            this.btn_size.ZoomSpeed = 10;
            this.btn_size.Click += new System.EventHandler(this.bunifuImageButton3_Click);
            // 
            // btn_Mini
            // 
            this.btn_Mini.ActiveImage = null;
            this.btn_Mini.AllowAnimations = true;
            this.btn_Mini.AllowBuffering = false;
            this.btn_Mini.AllowToggling = false;
            this.btn_Mini.AllowZooming = true;
            this.btn_Mini.AllowZoomingOnFocus = false;
            this.btn_Mini.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btn_Mini.BackColor = System.Drawing.Color.WhiteSmoke;
            this.btn_Mini.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_Mini.ErrorImage = ((System.Drawing.Image)(resources.GetObject("btn_Mini.ErrorImage")));
            this.btn_Mini.FadeWhenInactive = false;
            this.btn_Mini.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.btn_Mini.Image = ((System.Drawing.Image)(resources.GetObject("btn_Mini.Image")));
            this.btn_Mini.ImageActive = null;
            this.btn_Mini.ImageLocation = null;
            this.btn_Mini.ImageMargin = 0;
            this.btn_Mini.ImageSize = new System.Drawing.Size(19, 16);
            this.btn_Mini.ImageZoomSize = new System.Drawing.Size(20, 17);
            this.btn_Mini.InitialImage = ((System.Drawing.Image)(resources.GetObject("btn_Mini.InitialImage")));
            this.btn_Mini.Location = new System.Drawing.Point(725, 3);
            this.btn_Mini.Name = "btn_Mini";
            this.btn_Mini.Rotation = 0;
            this.btn_Mini.ShowActiveImage = true;
            this.btn_Mini.ShowCursorChanges = true;
            this.btn_Mini.ShowImageBorders = true;
            this.btn_Mini.ShowSizeMarkers = false;
            this.btn_Mini.Size = new System.Drawing.Size(20, 17);
            this.btn_Mini.TabIndex = 1;
            this.btn_Mini.ToolTipText = "";
            this.btn_Mini.WaitOnLoad = false;
            this.btn_Mini.Zoom = 0;
            this.btn_Mini.ZoomSpeed = 10;
            this.btn_Mini.Click += new System.EventHandler(this.bunifuImageButton2_Click);
            // 
            // btn_Thoat
            // 
            this.btn_Thoat.ActiveImage = null;
            this.btn_Thoat.AllowAnimations = true;
            this.btn_Thoat.AllowBuffering = false;
            this.btn_Thoat.AllowToggling = false;
            this.btn_Thoat.AllowZooming = true;
            this.btn_Thoat.AllowZoomingOnFocus = false;
            this.btn_Thoat.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btn_Thoat.BackColor = System.Drawing.Color.WhiteSmoke;
            this.btn_Thoat.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_Thoat.ErrorImage = ((System.Drawing.Image)(resources.GetObject("btn_Thoat.ErrorImage")));
            this.btn_Thoat.FadeWhenInactive = false;
            this.btn_Thoat.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.btn_Thoat.Image = ((System.Drawing.Image)(resources.GetObject("btn_Thoat.Image")));
            this.btn_Thoat.ImageActive = null;
            this.btn_Thoat.ImageLocation = null;
            this.btn_Thoat.ImageMargin = 0;
            this.btn_Thoat.ImageSize = new System.Drawing.Size(19, 16);
            this.btn_Thoat.ImageZoomSize = new System.Drawing.Size(20, 17);
            this.btn_Thoat.InitialImage = ((System.Drawing.Image)(resources.GetObject("btn_Thoat.InitialImage")));
            this.btn_Thoat.Location = new System.Drawing.Point(777, 3);
            this.btn_Thoat.Name = "btn_Thoat";
            this.btn_Thoat.Rotation = 0;
            this.btn_Thoat.ShowActiveImage = true;
            this.btn_Thoat.ShowCursorChanges = true;
            this.btn_Thoat.ShowImageBorders = true;
            this.btn_Thoat.ShowSizeMarkers = false;
            this.btn_Thoat.Size = new System.Drawing.Size(20, 17);
            this.btn_Thoat.TabIndex = 0;
            this.btn_Thoat.ToolTipText = "";
            this.btn_Thoat.WaitOnLoad = false;
            this.btn_Thoat.Zoom = 0;
            this.btn_Thoat.ZoomSpeed = 10;
            this.btn_Thoat.Click += new System.EventHandler(this.bunifuImageButton1_Click);
            // 
            // bunifuShadowPanel2
            // 
            this.bunifuShadowPanel2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel2.BorderColor = System.Drawing.Color.White;
            this.bunifuShadowPanel2.BorderRadius = 1;
            this.bunifuShadowPanel2.BorderThickness = 1;
            this.bunifuShadowPanel2.Controls.Add(this.bunifuImageButton1);
            this.bunifuShadowPanel2.Controls.Add(this.panel2);
            this.bunifuShadowPanel2.Controls.Add(this.pictureBox1);
            this.bunifuShadowPanel2.Controls.Add(this.btn_CaiDat);
            this.bunifuShadowPanel2.Controls.Add(this.btn_ThongKe);
            this.bunifuShadowPanel2.Controls.Add(this.btn_KhoHang);
            this.bunifuShadowPanel2.Controls.Add(this.btn_KhachHang);
            this.bunifuShadowPanel2.Controls.Add(this.btn_ThanhToan);
            this.bunifuShadowPanel2.Controls.Add(this.btn_PhongHat);
            this.bunifuShadowPanel2.Controls.Add(this.btn_TongQuan);
            this.bunifuShadowPanel2.Controls.Add(this.panel1);
            this.bunifuShadowPanel2.Dock = System.Windows.Forms.DockStyle.Left;
            this.bunifuShadowPanel2.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.bunifuShadowPanel2.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel2.Location = new System.Drawing.Point(0, 23);
            this.bunifuShadowPanel2.Margin = new System.Windows.Forms.Padding(0);
            this.bunifuShadowPanel2.Name = "bunifuShadowPanel2";
            this.bunifuShadowPanel2.PanelColor = System.Drawing.Color.White;
            this.bunifuShadowPanel2.PanelColor2 = System.Drawing.Color.White;
            this.bunifuShadowPanel2.ShadowColor = System.Drawing.Color.White;
            this.bunifuShadowPanel2.ShadowDept = 2;
            this.bunifuShadowPanel2.ShadowDepth = 3;
            this.bunifuShadowPanel2.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel2.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel2.Size = new System.Drawing.Size(203, 550);
            this.bunifuShadowPanel2.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel2.TabIndex = 1;
            this.bunifuShadowPanel2.ControlAdded += new System.Windows.Forms.ControlEventHandler(this.bunifuShadowPanel2_ControlAdded);
            // 
            // pictureBox1
            // 
            this.pictureBox1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(113)))), ((int)(((byte)(96)))), ((int)(((byte)(232)))));
            this.pictureBox1.Location = new System.Drawing.Point(0, 126);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(7, 52);
            this.pictureBox1.TabIndex = 17;
            this.pictureBox1.TabStop = false;
            // 
            // btn_CaiDat
            // 
            this.btn_CaiDat.AllowAnimations = true;
            this.btn_CaiDat.AllowMouseEffects = true;
            this.btn_CaiDat.AllowToggling = false;
            this.btn_CaiDat.AnimationSpeed = 200;
            this.btn_CaiDat.AutoGenerateColors = false;
            this.btn_CaiDat.AutoRoundBorders = false;
            this.btn_CaiDat.AutoSizeLeftIcon = true;
            this.btn_CaiDat.AutoSizeRightIcon = true;
            this.btn_CaiDat.BackColor = System.Drawing.Color.Transparent;
            this.btn_CaiDat.BackColor1 = System.Drawing.Color.White;
            this.btn_CaiDat.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_CaiDat.BackgroundImage")));
            this.btn_CaiDat.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_CaiDat.ButtonText = "Cài Đặt";
            this.btn_CaiDat.ButtonTextMarginLeft = 0;
            this.btn_CaiDat.ColorContrastOnClick = 45;
            this.btn_CaiDat.ColorContrastOnHover = 45;
            this.btn_CaiDat.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btn_CaiDat.CustomizableEdges = borderEdges8;
            this.btn_CaiDat.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_CaiDat.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_CaiDat.DisabledFillColor = System.Drawing.Color.White;
            this.btn_CaiDat.DisabledForecolor = System.Drawing.Color.DimGray;
            this.btn_CaiDat.Dock = System.Windows.Forms.DockStyle.Top;
            this.btn_CaiDat.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_CaiDat.Font = new System.Drawing.Font("Segoe UI Semibold", 15F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(186)));
            this.btn_CaiDat.ForeColor = System.Drawing.Color.DimGray;
            this.btn_CaiDat.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_CaiDat.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_CaiDat.IconLeftPadding = new System.Windows.Forms.Padding(22, 3, 3, 3);
            this.btn_CaiDat.IconMarginLeft = 11;
            this.btn_CaiDat.IconPadding = 18;
            this.btn_CaiDat.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_CaiDat.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_CaiDat.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_CaiDat.IconSize = 25;
            this.btn_CaiDat.IdleBorderColor = System.Drawing.Color.White;
            this.btn_CaiDat.IdleBorderRadius = 1;
            this.btn_CaiDat.IdleBorderThickness = 1;
            this.btn_CaiDat.IdleFillColor = System.Drawing.Color.White;
            this.btn_CaiDat.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btn_CaiDat.IdleIconLeftImage")));
            this.btn_CaiDat.IdleIconRightImage = null;
            this.btn_CaiDat.IndicateFocus = false;
            this.btn_CaiDat.Location = new System.Drawing.Point(0, 438);
            this.btn_CaiDat.Name = "btn_CaiDat";
            this.btn_CaiDat.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_CaiDat.OnDisabledState.BorderRadius = 1;
            this.btn_CaiDat.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_CaiDat.OnDisabledState.BorderThickness = 1;
            this.btn_CaiDat.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.btn_CaiDat.OnDisabledState.ForeColor = System.Drawing.Color.DimGray;
            this.btn_CaiDat.OnDisabledState.IconLeftImage = null;
            this.btn_CaiDat.OnDisabledState.IconRightImage = null;
            this.btn_CaiDat.onHoverState.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.btn_CaiDat.onHoverState.BorderRadius = 1;
            this.btn_CaiDat.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_CaiDat.onHoverState.BorderThickness = 1;
            this.btn_CaiDat.onHoverState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btn_CaiDat.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(113)))), ((int)(((byte)(96)))), ((int)(((byte)(232)))));
            this.btn_CaiDat.onHoverState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage")));
            this.btn_CaiDat.onHoverState.IconRightImage = null;
            this.btn_CaiDat.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btn_CaiDat.OnIdleState.BorderRadius = 1;
            this.btn_CaiDat.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_CaiDat.OnIdleState.BorderThickness = 1;
            this.btn_CaiDat.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btn_CaiDat.OnIdleState.ForeColor = System.Drawing.Color.DimGray;
            this.btn_CaiDat.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btn_CaiDat.OnIdleState.IconLeftImage")));
            this.btn_CaiDat.OnIdleState.IconRightImage = null;
            this.btn_CaiDat.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btn_CaiDat.OnPressedState.BorderRadius = 1;
            this.btn_CaiDat.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_CaiDat.OnPressedState.BorderThickness = 1;
            this.btn_CaiDat.OnPressedState.FillColor = System.Drawing.Color.White;
            this.btn_CaiDat.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(113)))), ((int)(((byte)(96)))), ((int)(((byte)(232)))));
            this.btn_CaiDat.OnPressedState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage1")));
            this.btn_CaiDat.OnPressedState.IconRightImage = null;
            this.btn_CaiDat.Size = new System.Drawing.Size(203, 52);
            this.btn_CaiDat.TabIndex = 16;
            this.btn_CaiDat.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_CaiDat.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_CaiDat.TextMarginLeft = 0;
            this.btn_CaiDat.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_CaiDat.UseDefaultRadiusAndThickness = true;
            this.btn_CaiDat.Click += new System.EventHandler(this.btn_CaiDat_Click);
            // 
            // btn_ThongKe
            // 
            this.btn_ThongKe.AllowAnimations = true;
            this.btn_ThongKe.AllowMouseEffects = true;
            this.btn_ThongKe.AllowToggling = false;
            this.btn_ThongKe.AnimationSpeed = 200;
            this.btn_ThongKe.AutoGenerateColors = false;
            this.btn_ThongKe.AutoRoundBorders = false;
            this.btn_ThongKe.AutoSizeLeftIcon = true;
            this.btn_ThongKe.AutoSizeRightIcon = true;
            this.btn_ThongKe.BackColor = System.Drawing.Color.Transparent;
            this.btn_ThongKe.BackColor1 = System.Drawing.Color.White;
            this.btn_ThongKe.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_ThongKe.BackgroundImage")));
            this.btn_ThongKe.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_ThongKe.ButtonText = "Thống Kê";
            this.btn_ThongKe.ButtonTextMarginLeft = 0;
            this.btn_ThongKe.ColorContrastOnClick = 45;
            this.btn_ThongKe.ColorContrastOnHover = 45;
            this.btn_ThongKe.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.btn_ThongKe.CustomizableEdges = borderEdges9;
            this.btn_ThongKe.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_ThongKe.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_ThongKe.DisabledFillColor = System.Drawing.Color.White;
            this.btn_ThongKe.DisabledForecolor = System.Drawing.Color.DimGray;
            this.btn_ThongKe.Dock = System.Windows.Forms.DockStyle.Top;
            this.btn_ThongKe.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_ThongKe.Font = new System.Drawing.Font("Segoe UI Semibold", 15F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(186)));
            this.btn_ThongKe.ForeColor = System.Drawing.Color.DimGray;
            this.btn_ThongKe.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_ThongKe.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_ThongKe.IconLeftPadding = new System.Windows.Forms.Padding(22, 3, 3, 3);
            this.btn_ThongKe.IconMarginLeft = 11;
            this.btn_ThongKe.IconPadding = 18;
            this.btn_ThongKe.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_ThongKe.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_ThongKe.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_ThongKe.IconSize = 25;
            this.btn_ThongKe.IdleBorderColor = System.Drawing.Color.White;
            this.btn_ThongKe.IdleBorderRadius = 1;
            this.btn_ThongKe.IdleBorderThickness = 1;
            this.btn_ThongKe.IdleFillColor = System.Drawing.Color.White;
            this.btn_ThongKe.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btn_ThongKe.IdleIconLeftImage")));
            this.btn_ThongKe.IdleIconRightImage = null;
            this.btn_ThongKe.IndicateFocus = false;
            this.btn_ThongKe.Location = new System.Drawing.Point(0, 386);
            this.btn_ThongKe.Name = "btn_ThongKe";
            this.btn_ThongKe.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_ThongKe.OnDisabledState.BorderRadius = 1;
            this.btn_ThongKe.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_ThongKe.OnDisabledState.BorderThickness = 1;
            this.btn_ThongKe.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.btn_ThongKe.OnDisabledState.ForeColor = System.Drawing.Color.DimGray;
            this.btn_ThongKe.OnDisabledState.IconLeftImage = null;
            this.btn_ThongKe.OnDisabledState.IconRightImage = null;
            this.btn_ThongKe.onHoverState.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.btn_ThongKe.onHoverState.BorderRadius = 1;
            this.btn_ThongKe.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_ThongKe.onHoverState.BorderThickness = 1;
            this.btn_ThongKe.onHoverState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btn_ThongKe.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(113)))), ((int)(((byte)(96)))), ((int)(((byte)(232)))));
            this.btn_ThongKe.onHoverState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage2")));
            this.btn_ThongKe.onHoverState.IconRightImage = null;
            this.btn_ThongKe.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btn_ThongKe.OnIdleState.BorderRadius = 1;
            this.btn_ThongKe.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_ThongKe.OnIdleState.BorderThickness = 1;
            this.btn_ThongKe.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btn_ThongKe.OnIdleState.ForeColor = System.Drawing.Color.DimGray;
            this.btn_ThongKe.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btn_ThongKe.OnIdleState.IconLeftImage")));
            this.btn_ThongKe.OnIdleState.IconRightImage = null;
            this.btn_ThongKe.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btn_ThongKe.OnPressedState.BorderRadius = 1;
            this.btn_ThongKe.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_ThongKe.OnPressedState.BorderThickness = 1;
            this.btn_ThongKe.OnPressedState.FillColor = System.Drawing.Color.White;
            this.btn_ThongKe.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(113)))), ((int)(((byte)(96)))), ((int)(((byte)(232)))));
            this.btn_ThongKe.OnPressedState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage3")));
            this.btn_ThongKe.OnPressedState.IconRightImage = null;
            this.btn_ThongKe.Size = new System.Drawing.Size(203, 52);
            this.btn_ThongKe.TabIndex = 15;
            this.btn_ThongKe.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_ThongKe.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_ThongKe.TextMarginLeft = 0;
            this.btn_ThongKe.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_ThongKe.UseDefaultRadiusAndThickness = true;
            this.btn_ThongKe.Click += new System.EventHandler(this.btn_ThongKe_Click);
            // 
            // btn_KhoHang
            // 
            this.btn_KhoHang.AllowAnimations = true;
            this.btn_KhoHang.AllowMouseEffects = true;
            this.btn_KhoHang.AllowToggling = false;
            this.btn_KhoHang.AnimationSpeed = 200;
            this.btn_KhoHang.AutoGenerateColors = false;
            this.btn_KhoHang.AutoRoundBorders = false;
            this.btn_KhoHang.AutoSizeLeftIcon = true;
            this.btn_KhoHang.AutoSizeRightIcon = true;
            this.btn_KhoHang.BackColor = System.Drawing.Color.Transparent;
            this.btn_KhoHang.BackColor1 = System.Drawing.Color.White;
            this.btn_KhoHang.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_KhoHang.BackgroundImage")));
            this.btn_KhoHang.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_KhoHang.ButtonText = "Kho Hàng";
            this.btn_KhoHang.ButtonTextMarginLeft = 0;
            this.btn_KhoHang.ColorContrastOnClick = 45;
            this.btn_KhoHang.ColorContrastOnHover = 45;
            this.btn_KhoHang.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges10.BottomLeft = true;
            borderEdges10.BottomRight = true;
            borderEdges10.TopLeft = true;
            borderEdges10.TopRight = true;
            this.btn_KhoHang.CustomizableEdges = borderEdges10;
            this.btn_KhoHang.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_KhoHang.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_KhoHang.DisabledFillColor = System.Drawing.Color.White;
            this.btn_KhoHang.DisabledForecolor = System.Drawing.Color.DimGray;
            this.btn_KhoHang.Dock = System.Windows.Forms.DockStyle.Top;
            this.btn_KhoHang.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_KhoHang.Font = new System.Drawing.Font("Segoe UI Semibold", 15F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(186)));
            this.btn_KhoHang.ForeColor = System.Drawing.Color.DimGray;
            this.btn_KhoHang.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_KhoHang.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_KhoHang.IconLeftPadding = new System.Windows.Forms.Padding(22, 3, 3, 3);
            this.btn_KhoHang.IconMarginLeft = 11;
            this.btn_KhoHang.IconPadding = 18;
            this.btn_KhoHang.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_KhoHang.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_KhoHang.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_KhoHang.IconSize = 25;
            this.btn_KhoHang.IdleBorderColor = System.Drawing.Color.White;
            this.btn_KhoHang.IdleBorderRadius = 1;
            this.btn_KhoHang.IdleBorderThickness = 1;
            this.btn_KhoHang.IdleFillColor = System.Drawing.Color.White;
            this.btn_KhoHang.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btn_KhoHang.IdleIconLeftImage")));
            this.btn_KhoHang.IdleIconRightImage = null;
            this.btn_KhoHang.IndicateFocus = false;
            this.btn_KhoHang.Location = new System.Drawing.Point(0, 334);
            this.btn_KhoHang.Name = "btn_KhoHang";
            this.btn_KhoHang.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_KhoHang.OnDisabledState.BorderRadius = 1;
            this.btn_KhoHang.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_KhoHang.OnDisabledState.BorderThickness = 1;
            this.btn_KhoHang.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.btn_KhoHang.OnDisabledState.ForeColor = System.Drawing.Color.DimGray;
            this.btn_KhoHang.OnDisabledState.IconLeftImage = null;
            this.btn_KhoHang.OnDisabledState.IconRightImage = null;
            this.btn_KhoHang.onHoverState.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.btn_KhoHang.onHoverState.BorderRadius = 1;
            this.btn_KhoHang.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_KhoHang.onHoverState.BorderThickness = 1;
            this.btn_KhoHang.onHoverState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btn_KhoHang.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(113)))), ((int)(((byte)(96)))), ((int)(((byte)(232)))));
            this.btn_KhoHang.onHoverState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage4")));
            this.btn_KhoHang.onHoverState.IconRightImage = null;
            this.btn_KhoHang.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btn_KhoHang.OnIdleState.BorderRadius = 1;
            this.btn_KhoHang.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_KhoHang.OnIdleState.BorderThickness = 1;
            this.btn_KhoHang.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btn_KhoHang.OnIdleState.ForeColor = System.Drawing.Color.DimGray;
            this.btn_KhoHang.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btn_KhoHang.OnIdleState.IconLeftImage")));
            this.btn_KhoHang.OnIdleState.IconRightImage = null;
            this.btn_KhoHang.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btn_KhoHang.OnPressedState.BorderRadius = 1;
            this.btn_KhoHang.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_KhoHang.OnPressedState.BorderThickness = 1;
            this.btn_KhoHang.OnPressedState.FillColor = System.Drawing.Color.White;
            this.btn_KhoHang.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(113)))), ((int)(((byte)(96)))), ((int)(((byte)(232)))));
            this.btn_KhoHang.OnPressedState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage5")));
            this.btn_KhoHang.OnPressedState.IconRightImage = null;
            this.btn_KhoHang.Size = new System.Drawing.Size(203, 52);
            this.btn_KhoHang.TabIndex = 14;
            this.btn_KhoHang.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_KhoHang.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_KhoHang.TextMarginLeft = 0;
            this.btn_KhoHang.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_KhoHang.UseDefaultRadiusAndThickness = true;
            this.btn_KhoHang.Click += new System.EventHandler(this.btn_KhoHang_Click);
            // 
            // btn_KhachHang
            // 
            this.btn_KhachHang.AllowAnimations = true;
            this.btn_KhachHang.AllowMouseEffects = true;
            this.btn_KhachHang.AllowToggling = false;
            this.btn_KhachHang.AnimationSpeed = 200;
            this.btn_KhachHang.AutoGenerateColors = false;
            this.btn_KhachHang.AutoRoundBorders = false;
            this.btn_KhachHang.AutoSizeLeftIcon = true;
            this.btn_KhachHang.AutoSizeRightIcon = true;
            this.btn_KhachHang.BackColor = System.Drawing.Color.Transparent;
            this.btn_KhachHang.BackColor1 = System.Drawing.Color.White;
            this.btn_KhachHang.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_KhachHang.BackgroundImage")));
            this.btn_KhachHang.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_KhachHang.ButtonText = "Khách Hàng";
            this.btn_KhachHang.ButtonTextMarginLeft = 0;
            this.btn_KhachHang.ColorContrastOnClick = 45;
            this.btn_KhachHang.ColorContrastOnHover = 45;
            this.btn_KhachHang.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges11.BottomLeft = true;
            borderEdges11.BottomRight = true;
            borderEdges11.TopLeft = true;
            borderEdges11.TopRight = true;
            this.btn_KhachHang.CustomizableEdges = borderEdges11;
            this.btn_KhachHang.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_KhachHang.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_KhachHang.DisabledFillColor = System.Drawing.Color.White;
            this.btn_KhachHang.DisabledForecolor = System.Drawing.Color.DimGray;
            this.btn_KhachHang.Dock = System.Windows.Forms.DockStyle.Top;
            this.btn_KhachHang.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_KhachHang.Font = new System.Drawing.Font("Segoe UI Semibold", 15F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(186)));
            this.btn_KhachHang.ForeColor = System.Drawing.Color.DimGray;
            this.btn_KhachHang.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_KhachHang.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_KhachHang.IconLeftPadding = new System.Windows.Forms.Padding(22, 3, 3, 3);
            this.btn_KhachHang.IconMarginLeft = 11;
            this.btn_KhachHang.IconPadding = 18;
            this.btn_KhachHang.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_KhachHang.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_KhachHang.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_KhachHang.IconSize = 25;
            this.btn_KhachHang.IdleBorderColor = System.Drawing.Color.White;
            this.btn_KhachHang.IdleBorderRadius = 1;
            this.btn_KhachHang.IdleBorderThickness = 1;
            this.btn_KhachHang.IdleFillColor = System.Drawing.Color.White;
            this.btn_KhachHang.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btn_KhachHang.IdleIconLeftImage")));
            this.btn_KhachHang.IdleIconRightImage = null;
            this.btn_KhachHang.IndicateFocus = false;
            this.btn_KhachHang.Location = new System.Drawing.Point(0, 282);
            this.btn_KhachHang.Name = "btn_KhachHang";
            this.btn_KhachHang.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_KhachHang.OnDisabledState.BorderRadius = 1;
            this.btn_KhachHang.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_KhachHang.OnDisabledState.BorderThickness = 1;
            this.btn_KhachHang.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.btn_KhachHang.OnDisabledState.ForeColor = System.Drawing.Color.DimGray;
            this.btn_KhachHang.OnDisabledState.IconLeftImage = null;
            this.btn_KhachHang.OnDisabledState.IconRightImage = null;
            this.btn_KhachHang.onHoverState.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.btn_KhachHang.onHoverState.BorderRadius = 1;
            this.btn_KhachHang.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_KhachHang.onHoverState.BorderThickness = 1;
            this.btn_KhachHang.onHoverState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btn_KhachHang.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(113)))), ((int)(((byte)(96)))), ((int)(((byte)(232)))));
            this.btn_KhachHang.onHoverState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage6")));
            this.btn_KhachHang.onHoverState.IconRightImage = null;
            this.btn_KhachHang.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btn_KhachHang.OnIdleState.BorderRadius = 1;
            this.btn_KhachHang.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_KhachHang.OnIdleState.BorderThickness = 1;
            this.btn_KhachHang.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btn_KhachHang.OnIdleState.ForeColor = System.Drawing.Color.DimGray;
            this.btn_KhachHang.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btn_KhachHang.OnIdleState.IconLeftImage")));
            this.btn_KhachHang.OnIdleState.IconRightImage = null;
            this.btn_KhachHang.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btn_KhachHang.OnPressedState.BorderRadius = 1;
            this.btn_KhachHang.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_KhachHang.OnPressedState.BorderThickness = 1;
            this.btn_KhachHang.OnPressedState.FillColor = System.Drawing.Color.White;
            this.btn_KhachHang.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(113)))), ((int)(((byte)(96)))), ((int)(((byte)(232)))));
            this.btn_KhachHang.OnPressedState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage7")));
            this.btn_KhachHang.OnPressedState.IconRightImage = null;
            this.btn_KhachHang.Size = new System.Drawing.Size(203, 52);
            this.btn_KhachHang.TabIndex = 13;
            this.btn_KhachHang.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_KhachHang.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_KhachHang.TextMarginLeft = 0;
            this.btn_KhachHang.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_KhachHang.UseDefaultRadiusAndThickness = true;
            this.btn_KhachHang.Click += new System.EventHandler(this.btn_KhachHang_Click);
            // 
            // btn_ThanhToan
            // 
            this.btn_ThanhToan.AllowAnimations = true;
            this.btn_ThanhToan.AllowMouseEffects = true;
            this.btn_ThanhToan.AllowToggling = false;
            this.btn_ThanhToan.AnimationSpeed = 200;
            this.btn_ThanhToan.AutoGenerateColors = false;
            this.btn_ThanhToan.AutoRoundBorders = false;
            this.btn_ThanhToan.AutoSizeLeftIcon = true;
            this.btn_ThanhToan.AutoSizeRightIcon = true;
            this.btn_ThanhToan.BackColor = System.Drawing.Color.Transparent;
            this.btn_ThanhToan.BackColor1 = System.Drawing.Color.White;
            this.btn_ThanhToan.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_ThanhToan.BackgroundImage")));
            this.btn_ThanhToan.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_ThanhToan.ButtonText = "Thanh Toán";
            this.btn_ThanhToan.ButtonTextMarginLeft = 0;
            this.btn_ThanhToan.ColorContrastOnClick = 45;
            this.btn_ThanhToan.ColorContrastOnHover = 45;
            this.btn_ThanhToan.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges12.BottomLeft = true;
            borderEdges12.BottomRight = true;
            borderEdges12.TopLeft = true;
            borderEdges12.TopRight = true;
            this.btn_ThanhToan.CustomizableEdges = borderEdges12;
            this.btn_ThanhToan.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_ThanhToan.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_ThanhToan.DisabledFillColor = System.Drawing.Color.White;
            this.btn_ThanhToan.DisabledForecolor = System.Drawing.Color.DimGray;
            this.btn_ThanhToan.Dock = System.Windows.Forms.DockStyle.Top;
            this.btn_ThanhToan.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_ThanhToan.Font = new System.Drawing.Font("Segoe UI Semibold", 15F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(186)));
            this.btn_ThanhToan.ForeColor = System.Drawing.Color.DimGray;
            this.btn_ThanhToan.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_ThanhToan.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_ThanhToan.IconLeftPadding = new System.Windows.Forms.Padding(22, 3, 3, 3);
            this.btn_ThanhToan.IconMarginLeft = 11;
            this.btn_ThanhToan.IconPadding = 18;
            this.btn_ThanhToan.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_ThanhToan.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_ThanhToan.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_ThanhToan.IconSize = 25;
            this.btn_ThanhToan.IdleBorderColor = System.Drawing.Color.White;
            this.btn_ThanhToan.IdleBorderRadius = 1;
            this.btn_ThanhToan.IdleBorderThickness = 1;
            this.btn_ThanhToan.IdleFillColor = System.Drawing.Color.White;
            this.btn_ThanhToan.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btn_ThanhToan.IdleIconLeftImage")));
            this.btn_ThanhToan.IdleIconRightImage = null;
            this.btn_ThanhToan.IndicateFocus = false;
            this.btn_ThanhToan.Location = new System.Drawing.Point(0, 230);
            this.btn_ThanhToan.Name = "btn_ThanhToan";
            this.btn_ThanhToan.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_ThanhToan.OnDisabledState.BorderRadius = 1;
            this.btn_ThanhToan.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_ThanhToan.OnDisabledState.BorderThickness = 1;
            this.btn_ThanhToan.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.btn_ThanhToan.OnDisabledState.ForeColor = System.Drawing.Color.DimGray;
            this.btn_ThanhToan.OnDisabledState.IconLeftImage = null;
            this.btn_ThanhToan.OnDisabledState.IconRightImage = null;
            this.btn_ThanhToan.onHoverState.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.btn_ThanhToan.onHoverState.BorderRadius = 1;
            this.btn_ThanhToan.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_ThanhToan.onHoverState.BorderThickness = 1;
            this.btn_ThanhToan.onHoverState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btn_ThanhToan.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(113)))), ((int)(((byte)(96)))), ((int)(((byte)(232)))));
            this.btn_ThanhToan.onHoverState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage8")));
            this.btn_ThanhToan.onHoverState.IconRightImage = null;
            this.btn_ThanhToan.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btn_ThanhToan.OnIdleState.BorderRadius = 1;
            this.btn_ThanhToan.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_ThanhToan.OnIdleState.BorderThickness = 1;
            this.btn_ThanhToan.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btn_ThanhToan.OnIdleState.ForeColor = System.Drawing.Color.DimGray;
            this.btn_ThanhToan.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btn_ThanhToan.OnIdleState.IconLeftImage")));
            this.btn_ThanhToan.OnIdleState.IconRightImage = null;
            this.btn_ThanhToan.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btn_ThanhToan.OnPressedState.BorderRadius = 1;
            this.btn_ThanhToan.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_ThanhToan.OnPressedState.BorderThickness = 1;
            this.btn_ThanhToan.OnPressedState.FillColor = System.Drawing.Color.White;
            this.btn_ThanhToan.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(113)))), ((int)(((byte)(96)))), ((int)(((byte)(232)))));
            this.btn_ThanhToan.OnPressedState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage9")));
            this.btn_ThanhToan.OnPressedState.IconRightImage = null;
            this.btn_ThanhToan.Size = new System.Drawing.Size(203, 52);
            this.btn_ThanhToan.TabIndex = 12;
            this.btn_ThanhToan.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_ThanhToan.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_ThanhToan.TextMarginLeft = 0;
            this.btn_ThanhToan.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_ThanhToan.UseDefaultRadiusAndThickness = true;
            this.btn_ThanhToan.Click += new System.EventHandler(this.btn_ThanhToan_Click);
            // 
            // btn_PhongHat
            // 
            this.btn_PhongHat.AllowAnimations = true;
            this.btn_PhongHat.AllowMouseEffects = true;
            this.btn_PhongHat.AllowToggling = false;
            this.btn_PhongHat.AnimationSpeed = 200;
            this.btn_PhongHat.AutoGenerateColors = false;
            this.btn_PhongHat.AutoRoundBorders = false;
            this.btn_PhongHat.AutoSizeLeftIcon = true;
            this.btn_PhongHat.AutoSizeRightIcon = true;
            this.btn_PhongHat.BackColor = System.Drawing.Color.Transparent;
            this.btn_PhongHat.BackColor1 = System.Drawing.Color.White;
            this.btn_PhongHat.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_PhongHat.BackgroundImage")));
            this.btn_PhongHat.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_PhongHat.ButtonText = "Phòng Hát";
            this.btn_PhongHat.ButtonTextMarginLeft = 0;
            this.btn_PhongHat.ColorContrastOnClick = 45;
            this.btn_PhongHat.ColorContrastOnHover = 45;
            this.btn_PhongHat.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges13.BottomLeft = true;
            borderEdges13.BottomRight = true;
            borderEdges13.TopLeft = true;
            borderEdges13.TopRight = true;
            this.btn_PhongHat.CustomizableEdges = borderEdges13;
            this.btn_PhongHat.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_PhongHat.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_PhongHat.DisabledFillColor = System.Drawing.Color.White;
            this.btn_PhongHat.DisabledForecolor = System.Drawing.Color.DimGray;
            this.btn_PhongHat.Dock = System.Windows.Forms.DockStyle.Top;
            this.btn_PhongHat.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_PhongHat.Font = new System.Drawing.Font("Segoe UI Semibold", 15F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(186)));
            this.btn_PhongHat.ForeColor = System.Drawing.Color.DimGray;
            this.btn_PhongHat.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_PhongHat.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_PhongHat.IconLeftPadding = new System.Windows.Forms.Padding(22, 3, 3, 3);
            this.btn_PhongHat.IconMarginLeft = 11;
            this.btn_PhongHat.IconPadding = 18;
            this.btn_PhongHat.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_PhongHat.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_PhongHat.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_PhongHat.IconSize = 25;
            this.btn_PhongHat.IdleBorderColor = System.Drawing.Color.White;
            this.btn_PhongHat.IdleBorderRadius = 1;
            this.btn_PhongHat.IdleBorderThickness = 1;
            this.btn_PhongHat.IdleFillColor = System.Drawing.Color.White;
            this.btn_PhongHat.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btn_PhongHat.IdleIconLeftImage")));
            this.btn_PhongHat.IdleIconRightImage = null;
            this.btn_PhongHat.IndicateFocus = false;
            this.btn_PhongHat.Location = new System.Drawing.Point(0, 178);
            this.btn_PhongHat.Name = "btn_PhongHat";
            this.btn_PhongHat.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_PhongHat.OnDisabledState.BorderRadius = 1;
            this.btn_PhongHat.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_PhongHat.OnDisabledState.BorderThickness = 1;
            this.btn_PhongHat.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.btn_PhongHat.OnDisabledState.ForeColor = System.Drawing.Color.DimGray;
            this.btn_PhongHat.OnDisabledState.IconLeftImage = null;
            this.btn_PhongHat.OnDisabledState.IconRightImage = null;
            this.btn_PhongHat.onHoverState.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.btn_PhongHat.onHoverState.BorderRadius = 1;
            this.btn_PhongHat.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_PhongHat.onHoverState.BorderThickness = 1;
            this.btn_PhongHat.onHoverState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btn_PhongHat.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(113)))), ((int)(((byte)(96)))), ((int)(((byte)(232)))));
            this.btn_PhongHat.onHoverState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage10")));
            this.btn_PhongHat.onHoverState.IconRightImage = null;
            this.btn_PhongHat.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btn_PhongHat.OnIdleState.BorderRadius = 1;
            this.btn_PhongHat.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_PhongHat.OnIdleState.BorderThickness = 1;
            this.btn_PhongHat.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btn_PhongHat.OnIdleState.ForeColor = System.Drawing.Color.DimGray;
            this.btn_PhongHat.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btn_PhongHat.OnIdleState.IconLeftImage")));
            this.btn_PhongHat.OnIdleState.IconRightImage = null;
            this.btn_PhongHat.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btn_PhongHat.OnPressedState.BorderRadius = 1;
            this.btn_PhongHat.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_PhongHat.OnPressedState.BorderThickness = 1;
            this.btn_PhongHat.OnPressedState.FillColor = System.Drawing.Color.White;
            this.btn_PhongHat.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(113)))), ((int)(((byte)(96)))), ((int)(((byte)(232)))));
            this.btn_PhongHat.OnPressedState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage11")));
            this.btn_PhongHat.OnPressedState.IconRightImage = null;
            this.btn_PhongHat.Size = new System.Drawing.Size(203, 52);
            this.btn_PhongHat.TabIndex = 11;
            this.btn_PhongHat.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_PhongHat.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_PhongHat.TextMarginLeft = 0;
            this.btn_PhongHat.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_PhongHat.UseDefaultRadiusAndThickness = true;
            this.btn_PhongHat.Click += new System.EventHandler(this.btn_PhongHat_Click);
            // 
            // btn_TongQuan
            // 
            this.btn_TongQuan.AllowAnimations = true;
            this.btn_TongQuan.AllowMouseEffects = true;
            this.btn_TongQuan.AllowToggling = false;
            this.btn_TongQuan.AnimationSpeed = 200;
            this.btn_TongQuan.AutoGenerateColors = false;
            this.btn_TongQuan.AutoRoundBorders = false;
            this.btn_TongQuan.AutoSizeLeftIcon = true;
            this.btn_TongQuan.AutoSizeRightIcon = true;
            this.btn_TongQuan.BackColor = System.Drawing.Color.Transparent;
            this.btn_TongQuan.BackColor1 = System.Drawing.Color.White;
            this.btn_TongQuan.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_TongQuan.BackgroundImage")));
            this.btn_TongQuan.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_TongQuan.ButtonText = "Tổng Quan";
            this.btn_TongQuan.ButtonTextMarginLeft = 0;
            this.btn_TongQuan.ColorContrastOnClick = 45;
            this.btn_TongQuan.ColorContrastOnHover = 45;
            this.btn_TongQuan.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges14.BottomLeft = true;
            borderEdges14.BottomRight = true;
            borderEdges14.TopLeft = true;
            borderEdges14.TopRight = true;
            this.btn_TongQuan.CustomizableEdges = borderEdges14;
            this.btn_TongQuan.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_TongQuan.DisabledBorderColor = System.Drawing.Color.WhiteSmoke;
            this.btn_TongQuan.DisabledFillColor = System.Drawing.Color.White;
            this.btn_TongQuan.DisabledForecolor = System.Drawing.Color.DimGray;
            this.btn_TongQuan.Dock = System.Windows.Forms.DockStyle.Top;
            this.btn_TongQuan.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_TongQuan.Font = new System.Drawing.Font("Segoe UI Semibold", 15F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(186)));
            this.btn_TongQuan.ForeColor = System.Drawing.Color.DimGray;
            this.btn_TongQuan.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_TongQuan.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_TongQuan.IconLeftPadding = new System.Windows.Forms.Padding(22, 3, 3, 3);
            this.btn_TongQuan.IconMarginLeft = 11;
            this.btn_TongQuan.IconPadding = 18;
            this.btn_TongQuan.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_TongQuan.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_TongQuan.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_TongQuan.IconSize = 25;
            this.btn_TongQuan.IdleBorderColor = System.Drawing.Color.White;
            this.btn_TongQuan.IdleBorderRadius = 1;
            this.btn_TongQuan.IdleBorderThickness = 1;
            this.btn_TongQuan.IdleFillColor = System.Drawing.Color.White;
            this.btn_TongQuan.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btn_TongQuan.IdleIconLeftImage")));
            this.btn_TongQuan.IdleIconRightImage = null;
            this.btn_TongQuan.IndicateFocus = false;
            this.btn_TongQuan.Location = new System.Drawing.Point(0, 126);
            this.btn_TongQuan.Name = "btn_TongQuan";
            this.btn_TongQuan.OnDisabledState.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.btn_TongQuan.OnDisabledState.BorderRadius = 1;
            this.btn_TongQuan.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_TongQuan.OnDisabledState.BorderThickness = 1;
            this.btn_TongQuan.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.btn_TongQuan.OnDisabledState.ForeColor = System.Drawing.Color.DimGray;
            this.btn_TongQuan.OnDisabledState.IconLeftImage = null;
            this.btn_TongQuan.OnDisabledState.IconRightImage = null;
            this.btn_TongQuan.onHoverState.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.btn_TongQuan.onHoverState.BorderRadius = 1;
            this.btn_TongQuan.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_TongQuan.onHoverState.BorderThickness = 1;
            this.btn_TongQuan.onHoverState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btn_TongQuan.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(113)))), ((int)(((byte)(96)))), ((int)(((byte)(232)))));
            this.btn_TongQuan.onHoverState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage12")));
            this.btn_TongQuan.onHoverState.IconRightImage = null;
            this.btn_TongQuan.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btn_TongQuan.OnIdleState.BorderRadius = 1;
            this.btn_TongQuan.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_TongQuan.OnIdleState.BorderThickness = 1;
            this.btn_TongQuan.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btn_TongQuan.OnIdleState.ForeColor = System.Drawing.Color.DimGray;
            this.btn_TongQuan.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btn_TongQuan.OnIdleState.IconLeftImage")));
            this.btn_TongQuan.OnIdleState.IconRightImage = null;
            this.btn_TongQuan.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btn_TongQuan.OnPressedState.BorderRadius = 1;
            this.btn_TongQuan.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_TongQuan.OnPressedState.BorderThickness = 1;
            this.btn_TongQuan.OnPressedState.FillColor = System.Drawing.Color.White;
            this.btn_TongQuan.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(113)))), ((int)(((byte)(96)))), ((int)(((byte)(232)))));
            this.btn_TongQuan.OnPressedState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage13")));
            this.btn_TongQuan.OnPressedState.IconRightImage = null;
            this.btn_TongQuan.Size = new System.Drawing.Size(203, 52);
            this.btn_TongQuan.TabIndex = 10;
            this.btn_TongQuan.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_TongQuan.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_TongQuan.TextMarginLeft = 0;
            this.btn_TongQuan.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_TongQuan.UseDefaultRadiusAndThickness = true;
            this.btn_TongQuan.Click += new System.EventHandler(this.btn_TrangChu_Click);
            // 
            // panel1
            // 
            this.panel1.Controls.Add(this.lb_ChucVu);
            this.panel1.Controls.Add(this.lb_TenNV);
            this.panel1.Controls.Add(this.bunifuPictureBox1);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(203, 126);
            this.panel1.TabIndex = 9;
            // 
            // lb_ChucVu
            // 
            this.lb_ChucVu.AutoSize = true;
            this.lb_ChucVu.Location = new System.Drawing.Point(78, 97);
            this.lb_ChucVu.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lb_ChucVu.Name = "lb_ChucVu";
            this.lb_ChucVu.Size = new System.Drawing.Size(36, 13);
            this.lb_ChucVu.TabIndex = 2;
            this.lb_ChucVu.Text = "Admin";
            // 
            // lb_TenNV
            // 
            this.lb_TenNV.AutoSize = true;
            this.lb_TenNV.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lb_TenNV.Location = new System.Drawing.Point(34, 73);
            this.lb_TenNV.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lb_TenNV.Name = "lb_TenNV";
            this.lb_TenNV.Size = new System.Drawing.Size(126, 15);
            this.lb_TenNV.TabIndex = 1;
            this.lb_TenNV.Text = "Nguyễn Ngọc Niên";
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = true;
            this.bunifuPictureBox1.BorderRadius = 30;
            this.bunifuPictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox1.Image")));
            this.bunifuPictureBox1.IsCircle = true;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(67, 10);
            this.bunifuPictureBox1.Margin = new System.Windows.Forms.Padding(2);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(61, 61);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 0;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // bunifuShadowPanel3
            // 
            this.bunifuShadowPanel3.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel3.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel3.BorderRadius = 1;
            this.bunifuShadowPanel3.BorderThickness = 1;
            this.bunifuShadowPanel3.Controls.Add(this.panel3);
            this.bunifuShadowPanel3.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuShadowPanel3.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.bunifuShadowPanel3.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel3.Location = new System.Drawing.Point(203, 23);
            this.bunifuShadowPanel3.Margin = new System.Windows.Forms.Padding(0);
            this.bunifuShadowPanel3.Name = "bunifuShadowPanel3";
            this.bunifuShadowPanel3.PanelColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel3.PanelColor2 = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel3.ShadowColor = System.Drawing.Color.DarkGray;
            this.bunifuShadowPanel3.ShadowDept = 2;
            this.bunifuShadowPanel3.ShadowDepth = 3;
            this.bunifuShadowPanel3.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel3.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel3.Size = new System.Drawing.Size(597, 77);
            this.bunifuShadowPanel3.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel3.TabIndex = 2;
            // 
            // pnl_Con
            // 
            this.pnl_Con.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.pnl_Con.BackgroundColor = System.Drawing.Color.Transparent;
            this.pnl_Con.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pnl_Con.BackgroundImage")));
            this.pnl_Con.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pnl_Con.BorderColor = System.Drawing.Color.Transparent;
            this.pnl_Con.BorderRadius = 3;
            this.pnl_Con.BorderThickness = 1;
            this.pnl_Con.Location = new System.Drawing.Point(203, 103);
            this.pnl_Con.Name = "pnl_Con";
            this.pnl_Con.ShowBorders = true;
            this.pnl_Con.Size = new System.Drawing.Size(597, 467);
            this.pnl_Con.TabIndex = 3;
            // 
            // bunifuImageButton1
            // 
            this.bunifuImageButton1.ActiveImage = null;
            this.bunifuImageButton1.AllowAnimations = true;
            this.bunifuImageButton1.AllowBuffering = false;
            this.bunifuImageButton1.AllowToggling = false;
            this.bunifuImageButton1.AllowZooming = true;
            this.bunifuImageButton1.AllowZoomingOnFocus = false;
            this.bunifuImageButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuImageButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuImageButton1.ErrorImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton1.ErrorImage")));
            this.bunifuImageButton1.FadeWhenInactive = false;
            this.bunifuImageButton1.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.bunifuImageButton1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton1.Image")));
            this.bunifuImageButton1.ImageActive = null;
            this.bunifuImageButton1.ImageLocation = null;
            this.bunifuImageButton1.ImageMargin = 0;
            this.bunifuImageButton1.ImageSize = new System.Drawing.Size(28, 30);
            this.bunifuImageButton1.ImageZoomSize = new System.Drawing.Size(29, 31);
            this.bunifuImageButton1.InitialImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton1.InitialImage")));
            this.bunifuImageButton1.Location = new System.Drawing.Point(12, 507);
            this.bunifuImageButton1.Name = "bunifuImageButton1";
            this.bunifuImageButton1.Rotation = 0;
            this.bunifuImageButton1.ShowActiveImage = true;
            this.bunifuImageButton1.ShowCursorChanges = true;
            this.bunifuImageButton1.ShowImageBorders = true;
            this.bunifuImageButton1.ShowSizeMarkers = false;
            this.bunifuImageButton1.Size = new System.Drawing.Size(29, 31);
            this.bunifuImageButton1.TabIndex = 18;
            this.bunifuImageButton1.ToolTipText = "";
            this.bunifuImageButton1.WaitOnLoad = false;
            this.bunifuImageButton1.Zoom = 0;
            this.bunifuImageButton1.ZoomSpeed = 10;
            this.bunifuImageButton1.Click += new System.EventHandler(this.bunifuImageButton1_Click_1);
            // 
            // panel2
            // 
            this.panel2.BackColor = System.Drawing.Color.Blue;
            this.panel2.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.panel2.Location = new System.Drawing.Point(9, 488);
            this.panel2.Margin = new System.Windows.Forms.Padding(0);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(173, 2);
            this.panel2.TabIndex = 19;
            // 
            // panel3
            // 
            this.panel3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(113)))), ((int)(((byte)(96)))), ((int)(((byte)(232)))));
            this.panel3.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.panel3.Location = new System.Drawing.Point(19, 43);
            this.panel3.Margin = new System.Windows.Forms.Padding(0);
            this.panel3.Name = "panel3";
            this.panel3.Size = new System.Drawing.Size(109, 3);
            this.panel3.TabIndex = 20;
            // 
            // frmTrangChu
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(800, 573);
            this.Controls.Add(this.pnl_Con);
            this.Controls.Add(this.bunifuShadowPanel3);
            this.Controls.Add(this.bunifuShadowPanel2);
            this.Controls.Add(this.bunifuShadowPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "frmTrangChu";
            this.Text = "Form1";
            this.bunifuShadowPanel1.ResumeLayout(false);
            this.bunifuShadowPanel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.bunifuShadowPanel3.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuFormDock bunifuFormDock1;
        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel3;
        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel2;
        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_CaiDat;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_ThongKe;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_KhoHang;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_KhachHang;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_ThanhToan;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_PhongHat;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_TongQuan;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Label lb_ChucVu;
        private System.Windows.Forms.Label lb_TenNV;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        private System.Windows.Forms.PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuImageButton btn_Thoat;
        private Bunifu.UI.WinForms.BunifuImageButton btn_size;
        private Bunifu.UI.WinForms.BunifuImageButton btn_Mini;
        private Bunifu.UI.WinForms.BunifuPanel pnl_Con;
        private System.Windows.Forms.Panel panel2;
        private Bunifu.UI.WinForms.BunifuImageButton bunifuImageButton1;
        private System.Windows.Forms.Panel panel3;
    }
}